# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a1713aa2e3e6b3c0094c67eb6b9903bd32f5cbe59ef51cf668f25d4b9493a0b45131cb2abe793bf824e42bb7b5a65bec429aec2a2e82f773dc5f2d85cdff7375

test:
  secret_key_base: edbccb96d10ba9897a549e6b6c465481c72852d12ca87ed91227255f1284330d43a39de2a4d77f40e49a3a01f0a21661a24f5ede65ef368299511edec22112d3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
